### ISSUE TITLE
Error when attempting to Sign in

### ISSUE THREAD

**Issue by thanhctES** [kdgregory/example-cognito-java#2]
Hi Kdgregory!

Great sample and [blog post](http://blog.kdgregory.com/2016/12/server-side-authentication-with-amazon.html) !
But I got error when attempting to sign-in.

> Failed to load resource: the server responded with a status of 500 (User pool ap-southeast-XXXXX does not exist. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: eafaca1c-0ae6-11e8-a770-a5d5f3fa59c4))

I tried connect by javascript (VUEJS) It worked fine with User pool above. 
I watched this video: https://www.youtube.com/watch?v=TowcW1aTDqE&t=8991s 
I saw they used: 
      ClientId: 'xxxxxx',
      IdentityPoolId: 'xxxxx',
      UserPoolId: 'xxxx',
      region: 'xxxx'
as required variables. 
Thank you!

**Comment by thanhctES** [comment]
It's Ok if I create user pool without Federated Identities and set US East (Virginia) Region (us-east-1).

**Comment by kdgregory** [comment]
Really sorry about the late reply (apparently I don't have notifications turned on for this repo).

I believe this is because I created the `AWSCognitoIdentityProviderClient` directly. Most of the client constructors are deprecated because they don't make use of the default region provider ... which is something I never notice because I'm using `us-east-1` by default.

The correct solution would be to replace the client constructor with `...ClientBuilder.defaultClient()`.

**Comment by sergiomb2** [comment]
+1 , first thanks for this great example , I'm also facing this problem try 

    Unable to execute HTTP request: cognito-idp.us-east-1.amazonaws.com

when I set   <param-name>cognito_pool_id</param-name> with eu-central-1.something

Any quick solution around ? 

Thanks

**Comment by kdgregory** [comment]
@sergiomb2 - this is almost certainly because I use the default client constructor in [AbstractCognitoServlet](https://github.com/kdgregory/example-cognito-java/blob/master/src/main/java/com/kdgregory/example/cognito/servlets/AbstractCognitoServlet.java#L32). This constructor creates a client that assumes `us-east-1`.

There are two solutions: the first is to explicitly set the region after constructing the client (but before using it). The second, and better, is to use [AWSCognitoIdentityProviderClientBuilder](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cognitoidp/AWSCognitoIdentityProviderClientBuilder.html) rather than the constructor, because it attempts to identify the correct region. It may or may not be available in the version of the SDK (1.11.60) that I used for this example; it's certainly available in later revisions (currently 1.11.400-something).

Which brings up another point: this example is two years old, almost certainly is not an example of current best practice.

**Comment by sergiomb2** [comment]
Thank you, I fix it with some hard code [1], cognito_pool_id is correctly set but region is not set .
Yes java cognito api changed a lot and the code is a little deprecated and always end with error [2],  I will try use the new SDK . 
Thanks 

[1]

    AdminInitiateAuthRequest authRequest = new AdminInitiateAuthRequest()
                    .withAuthFlow(AuthFlowType.ADMIN_NO_SRP_AUTH)
                    .withAuthParameters(authParams)
                    .withClientId(cognitoClientId())
                    .withUserPoolId(cognitoPoolId());
    cognitoClient.setRegion(com.amazonaws.regions.Region.getRegion(Regions.EU_CENTRAL_1));
    AdminInitiateAuthResult authResponse = cognitoClient.adminInitiateAuth(authRequest);

[2] 

    The security token included in the request is invalid. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: UnrecognizedClientException;

**Comment by kdgregory** [comment]
@sergiomb2 - you should set the region immediately after creating the client, not at the time of making the request. I gave you a link in the previous comment as to where this should happen.

Regarding the invalid security token, I'm not sure why this is happening. It's possible that the API has changed. Are you sure that it's coming from this request?
